### ISSUE TITLE
kuromojiなどがdevDependenciesに含まれている

### ISSUE THREAD

**Issue by azu** [lostandfound/textlint-rule-ja-hiragana-fukushi#1]
npmとして公開するソースに含むライブラリは `devDependencies` ではなく、 `dependencies` に入れる必要があります。

- [ちゃんと使い分けてる? dependenciesいろいろ。 - Qiita](http://qiita.com/cognitom/items/acc3ffcbca4c56cf2b95 "ちゃんと使い分けてる? dependenciesいろいろ。 - Qiita")

```sh
# devDepsからアンインストール
npm uninstall --save-dev js-yaml kuromojin morpheme-match-all
# depsへインストール
npm install --save js-yaml kuromojin morpheme-match-all
```

**Comment by lostandfound** [comment]
ご指摘ありがとうございます！ 対応しました。
